logging.level.com.sfialok.ratelimiter=DEBUG
# Also useful to see the Redis interaction
logging.level.org.springframework.data.redis=DEBUG
rate-limiter-reactive.enabled=true
rate-limiter-reactive.refill-interval-ms=10000
rate-limiter-reactive.refill-rate=5
rate-limiter-reactive.capacity=5